version: '3'
services:
  nodejs:
    build: ./docker/nodejs
    tty: true
    volumes:
      - ./app:/app:cached
    ports:
      - "3000:3000"
  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./app/dist:/var/www/app/public:cached
